spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:MoayongApiTestDB

  h2:
    console:
      enabled: true
