spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/moa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    hikari:
      password: 1


jwt:
  secret: "b7f3e8a9d5c6a1e2f4b8d7e3c2a9f5d6"
  token-validity-in-seconds: 3600 #
  refresh-token-validity-in-seconds: 86400